# Generated by Django 4.2 on 2023-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankManagement',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('deposite', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
